/**
 * Writes agent-generated FAQ entries into the titans-abroad repo and pushes.
 * Vercel picks up the push and redeploys, so the answers go live without a
 * human in the loop.
 *
 * Safety rails, because this runs unsupervised every night:
 *  - only ever writes data/seo-faqs.ts, never existing page content
 *  - refuses to publish more than MAX_NEW_PER_RUN entries in one night
 *  - never replaces an entry that already exists for a keyword on a path
 *  - set SEO_AUTOPUBLISH=off to stop it without touching the workflow
 */

import { execFileSync } from "child_process";
import { readFileSync, writeFileSync, existsSync, mkdtempSync } from "fs";
import { join } from "path";
import { tmpdir } from "os";

export type FaqEntry = {
  keyword: string;
  question: string;
  answer: string;
  addedAt: string;
  positionAtGeneration: number;
};

const SITE_REPO = "tayyabali123/titans-abroad";
const SITE_BRANCH = process.env.SITE_BRANCH || "main";
const FAQ_FILE = "data/seo-faqs.ts";
const MAX_NEW_PER_RUN = 10;

const FILE_HEADER = `/**
 * FAQ sections generated by the SEO gap agent in the marble-wren repo.
 *
 * DO NOT EDIT BY HAND. The agent rewrites this whole file on every nightly run
 * that finds new near-miss keywords. Hand edits will be overwritten.
 *
 * The agent only ever appends question and answer pairs keyed by pathname. It
 * never touches existing page content, which keeps an unsupervised nightly
 * writer from being able to damage anything already published.
 */

export type SeoFaq = {
  /** The Search Console query this answer was written for. */
  keyword: string;
  question: string;
  answer: string;
  /** ISO date the agent generated this entry. */
  addedAt: string;
  /** Average position of the keyword when the entry was generated. */
  positionAtGeneration: number;
};

/** Keyed by pathname with no trailing slash. The homepage is "/". */
export const seoFaqs: Record<string, SeoFaq[]> = `;

const FILE_FOOTER = `;

export function getSeoFaqs(pathname: string): SeoFaq[] {
  const key = pathname === "/" ? "/" : pathname.replace(/\\/+$/, "");
  return seoFaqs[key] ?? [];
}
`;

export type PublishResult = {
  published: number;
  skipped: number;
  paths: string[];
  reason?: string;
};

function git(cwd: string, args: string[]): string {
  return execFileSync("git", args, { cwd, encoding: "utf-8" });
}

/** Pulls the pathname out of a full Search Console page URL. */
export function toPathname(pageUrl: string): string {
  try {
    const p = new URL(pageUrl).pathname;
    return p === "/" ? "/" : p.replace(/\/+$/, "");
  } catch {
    return pageUrl;
  }
}

/**
 * Reads the existing map out of the site repo's FAQ file. Parsing the literal
 * out of the TypeScript source keeps the site free of a build-time data fetch,
 * at the cost of this narrow bit of extraction.
 */
function readExisting(filePath: string): Record<string, FaqEntry[]> {
  if (!existsSync(filePath)) return {};
  const src = readFileSync(filePath, "utf-8");
  const start = src.indexOf("Record<string, SeoFaq[]> =");
  if (start === -1) return {};
  const open = src.indexOf("{", start);
  if (open === -1) return {};

  let depth = 0;
  let end = -1;
  let inString: string | null = null;
  for (let i = open; i < src.length; i++) {
    const ch = src[i];
    if (inString) {
      if (ch === "\\") i++;
      else if (ch === inString) inString = null;
      continue;
    }
    if (ch === '"' || ch === "'" || ch === "`") inString = ch;
    else if (ch === "{") depth++;
    else if (ch === "}") {
      depth--;
      if (depth === 0) {
        end = i + 1;
        break;
      }
    }
  }
  if (end === -1) return {};

  try {
    return JSON.parse(src.slice(open, end));
  } catch {
    console.warn("Could not parse existing FAQ map, starting from empty.");
    return {};
  }
}

export async function publishFaqs(candidates: Record<string, FaqEntry[]>): Promise<PublishResult> {
  if ((process.env.SEO_AUTOPUBLISH || "").toLowerCase() === "off") {
    return { published: 0, skipped: 0, paths: [], reason: "SEO_AUTOPUBLISH=off" };
  }

  const token = process.env.SITE_REPO_TOKEN;
  if (!token) {
    return { published: 0, skipped: 0, paths: [], reason: "SITE_REPO_TOKEN not set" };
  }

  const totalCandidates = Object.values(candidates).reduce((s, v) => s + v.length, 0);
  if (totalCandidates === 0) {
    return { published: 0, skipped: 0, paths: [], reason: "nothing to publish" };
  }

  const workdir = mkdtempSync(join(tmpdir(), "site-"));
  const repoUrl = `https://x-access-token:${token}@github.com/${SITE_REPO}.git`;

  console.log(`Cloning ${SITE_REPO}...`);
  git(workdir, ["clone", "--depth", "1", "--branch", SITE_BRANCH, repoUrl, "site"]);
  const repo = join(workdir, "site");

  const filePath = join(repo, FAQ_FILE);
  const existing = readExisting(filePath);

  let published = 0;
  let skipped = 0;
  const touched: string[] = [];

  for (const [path, entries] of Object.entries(candidates)) {
    const current = existing[path] ?? [];
    const seen = new Set(current.map((e) => e.keyword.toLowerCase()));

    for (const entry of entries) {
      if (published >= MAX_NEW_PER_RUN) {
        skipped++;
        continue;
      }
      if (seen.has(entry.keyword.toLowerCase())) {
        skipped++;
        continue;
      }
      current.push(entry);
      seen.add(entry.keyword.toLowerCase());
      published++;
      if (!touched.includes(path)) touched.push(path);
    }

    if (current.length > 0) existing[path] = current;
  }

  if (published === 0) {
    return { published: 0, skipped, paths: [], reason: "all candidates already published" };
  }

  const body = JSON.stringify(existing, null, 2);
  writeFileSync(filePath, FILE_HEADER + body + FILE_FOOTER, "utf-8");

  git(repo, ["config", "user.name", "seo-agent[bot]"]);
  git(repo, ["config", "user.email", "seo-agent@users.noreply.github.com"]);
  git(repo, ["add", FAQ_FILE]);

  const status = git(repo, ["status", "--porcelain"]).trim();
  if (!status) {
    return { published: 0, skipped, paths: [], reason: "file unchanged after write" };
  }

  const date = new Date().toISOString().split("T")[0];
  git(repo, ["commit", "-m", `seo: add ${published} FAQ ${published === 1 ? "answer" : "answers"} (${date})`]);
  git(repo, ["push", "origin", SITE_BRANCH]);

  console.log(`Pushed ${published} FAQ entries across ${touched.length} pages.`);
  return { published, skipped, paths: touched };
}
