/**
 * Writes what the agent generated into the titans-abroad repo and pushes.
 * Vercel picks up the push and redeploys, so the changes go live without a
 * human in the loop.
 *
 * Two agent-owned files, one clone, one commit:
 *   data/seo-faqs.ts   question and answer blocks keyed by pathname
 *   data/seo-links.ts  internal links that consolidate cannibalized queries
 *
 * Safety rails, because this runs unsupervised every night:
 *  - only ever writes those two files, never existing page content
 *  - caps how much it can add in one night
 *  - never replaces an entry that already exists
 *  - set SEO_AUTOPUBLISH=off to stop it without touching the workflow
 */

import { execFileSync } from "child_process";
import { readFileSync, writeFileSync, existsSync, mkdtempSync } from "fs";
import { join } from "path";
import { tmpdir } from "os";

export type FaqEntry = {
  keyword: string;
  question: string;
  answer: string;
  addedAt: string;
  positionAtGeneration: number;
};

export type LinkEntry = {
  href: string;
  anchor: string;
  addedAt: string;
};

const SITE_REPO = "tayyabali123/titans-abroad";
const SITE_BRANCH = process.env.SITE_BRANCH || "main";
const FAQ_FILE = "data/seo-faqs.ts";
const LINK_FILE = "data/seo-links.ts";
const MAX_FAQS_PER_RUN = 10;
const MAX_LINKS_PER_RUN = 20;

const FAQ_HEADER = `/**
 * FAQ sections generated by the SEO gap agent in the marble-wren repo.
 *
 * DO NOT EDIT BY HAND. The agent rewrites this whole file on every nightly run
 * that finds new near-miss keywords. Hand edits will be overwritten.
 *
 * The agent only ever appends question and answer pairs keyed by pathname. It
 * never touches existing page content, which keeps an unsupervised nightly
 * writer from being able to damage anything already published.
 */

export type SeoFaq = {
  /** The Search Console query this answer was written for. */
  keyword: string;
  question: string;
  answer: string;
  /** ISO date the agent generated this entry. */
  addedAt: string;
  /** Average position of the keyword when the entry was generated. */
  positionAtGeneration: number;
};

/** Keyed by pathname with no trailing slash. The homepage is "/". */
export const seoFaqs: Record<string, SeoFaq[]> = `;

const FAQ_FOOTER = `;

export function getSeoFaqs(pathname: string): SeoFaq[] {
  const key = pathname === "/" ? "/" : pathname.replace(/\\/+$/, "");
  return seoFaqs[key] ?? [];
}
`;

const LINK_HEADER = `/**
 * Internal links generated by the SEO agent in the marble-wren repo.
 *
 * DO NOT EDIT BY HAND. The agent rewrites this whole file whenever it finds
 * two of our own pages competing for the same query. Hand edits will be
 * overwritten.
 *
 * When Google sees two of our pages answering one query it has to pick, and
 * the split signal usually costs us both. The agent picks a primary page and
 * points a link at it from each of the others, using the query itself as the
 * anchor text.
 */

export type SeoLink = {
  /** Pathname of the primary page this links to. */
  href: string;
  /** Anchor text, which is the Search Console query being consolidated. */
  anchor: string;
  /** ISO date the agent added this link. */
  addedAt: string;
};

/** Keyed by the pathname the link appears ON, with no trailing slash. */
export const seoLinks: Record<string, SeoLink[]> = `;

const LINK_FOOTER = `;

export function getSeoLinks(pathname: string): SeoLink[] {
  const key = pathname === "/" ? "/" : pathname.replace(/\\/+$/, "");
  return seoLinks[key] ?? [];
}
`;

export type PublishResult = {
  faqsPublished: number;
  faqsSkipped: number;
  linksPublished: number;
  faqPaths: string[];
  linkPaths: string[];
  reason?: string;
};

function git(cwd: string, args: string[]): string {
  return execFileSync("git", args, { cwd, encoding: "utf-8" });
}

/** Pulls the pathname out of a full Search Console page URL. */
export function toPathname(pageUrl: string): string {
  try {
    const p = new URL(pageUrl).pathname;
    return p === "/" ? "/" : p.replace(/\/+$/, "");
  } catch {
    return pageUrl;
  }
}

/**
 * Reads an existing map out of the site repo's TypeScript source. Parsing the
 * literal keeps the site free of a build-time data fetch, at the cost of this
 * narrow bit of extraction.
 */
function readExisting<T>(filePath: string, marker: string): Record<string, T[]> {
  if (!existsSync(filePath)) return {};
  const src = readFileSync(filePath, "utf-8");
  const start = src.indexOf(marker);
  if (start === -1) return {};
  const open = src.indexOf("{", start);
  if (open === -1) return {};

  let depth = 0;
  let end = -1;
  let inString: string | null = null;
  for (let i = open; i < src.length; i++) {
    const ch = src[i];
    if (inString) {
      if (ch === "\\") i++;
      else if (ch === inString) inString = null;
      continue;
    }
    if (ch === '"' || ch === "'" || ch === "`") inString = ch;
    else if (ch === "{") depth++;
    else if (ch === "}") {
      depth--;
      if (depth === 0) {
        end = i + 1;
        break;
      }
    }
  }
  if (end === -1) return {};

  try {
    return JSON.parse(src.slice(open, end));
  } catch {
    console.warn(`Could not parse existing map in ${filePath}, starting from empty.`);
    return {};
  }
}

function mergeFaqs(
  existing: Record<string, FaqEntry[]>,
  candidates: Record<string, FaqEntry[]>
): { published: number; skipped: number; paths: string[] } {
  let published = 0;
  let skipped = 0;
  const paths: string[] = [];

  for (const [path, entries] of Object.entries(candidates)) {
    const current = existing[path] ?? [];
    const seen = new Set(current.map((e) => e.keyword.toLowerCase()));

    for (const entry of entries) {
      if (published >= MAX_FAQS_PER_RUN || seen.has(entry.keyword.toLowerCase())) {
        skipped++;
        continue;
      }
      current.push(entry);
      seen.add(entry.keyword.toLowerCase());
      published++;
      if (!paths.includes(path)) paths.push(path);
    }

    if (current.length > 0) existing[path] = current;
  }

  return { published, skipped, paths };
}

function mergeLinks(
  existing: Record<string, LinkEntry[]>,
  candidates: Record<string, LinkEntry[]>
): { published: number; paths: string[] } {
  let published = 0;
  const paths: string[] = [];

  for (const [path, entries] of Object.entries(candidates)) {
    const current = existing[path] ?? [];
    const seen = new Set(current.map((e) => e.href));

    for (const entry of entries) {
      // A page linking to itself is the one thing that would make the
      // cannibalization worse rather than better.
      if (published >= MAX_LINKS_PER_RUN || entry.href === path || seen.has(entry.href)) {
        continue;
      }
      current.push(entry);
      seen.add(entry.href);
      published++;
      if (!paths.includes(path)) paths.push(path);
    }

    if (current.length > 0) existing[path] = current;
  }

  return { published, paths };
}

export async function publishToSite(
  faqCandidates: Record<string, FaqEntry[]>,
  linkCandidates: Record<string, LinkEntry[]>
): Promise<PublishResult> {
  const empty: PublishResult = {
    faqsPublished: 0,
    faqsSkipped: 0,
    linksPublished: 0,
    faqPaths: [],
    linkPaths: [],
  };

  if ((process.env.SEO_AUTOPUBLISH || "").toLowerCase() === "off") {
    return { ...empty, reason: "SEO_AUTOPUBLISH=off" };
  }

  const token = process.env.SITE_REPO_TOKEN;
  if (!token) {
    return { ...empty, reason: "SITE_REPO_TOKEN not set" };
  }

  const totalCandidates =
    Object.values(faqCandidates).reduce((s, v) => s + v.length, 0) +
    Object.values(linkCandidates).reduce((s, v) => s + v.length, 0);
  if (totalCandidates === 0) {
    return { ...empty, reason: "nothing to publish" };
  }

  const workdir = mkdtempSync(join(tmpdir(), "site-"));
  const repoUrl = `https://x-access-token:${token}@github.com/${SITE_REPO}.git`;

  console.log(`Cloning ${SITE_REPO}...`);
  git(workdir, ["clone", "--depth", "1", "--branch", SITE_BRANCH, repoUrl, "site"]);
  const repo = join(workdir, "site");

  const faqPath = join(repo, FAQ_FILE);
  const linkPath = join(repo, LINK_FILE);

  const existingFaqs = readExisting<FaqEntry>(faqPath, "Record<string, SeoFaq[]> =");
  const existingLinks = readExisting<LinkEntry>(linkPath, "Record<string, SeoLink[]> =");

  const faqResult = mergeFaqs(existingFaqs, faqCandidates);
  const linkResult = mergeLinks(existingLinks, linkCandidates);

  if (faqResult.published === 0 && linkResult.published === 0) {
    return { ...empty, faqsSkipped: faqResult.skipped, reason: "everything already published" };
  }

  if (faqResult.published > 0) {
    writeFileSync(faqPath, FAQ_HEADER + JSON.stringify(existingFaqs, null, 2) + FAQ_FOOTER, "utf-8");
  }
  if (linkResult.published > 0) {
    writeFileSync(linkPath, LINK_HEADER + JSON.stringify(existingLinks, null, 2) + LINK_FOOTER, "utf-8");
  }

  git(repo, ["config", "user.name", "tayyabali123"]);
  git(repo, ["config", "user.email", "muhammadtayyabali868@gmail.com"]);
  git(repo, ["add", FAQ_FILE, LINK_FILE]);

  if (!git(repo, ["status", "--porcelain"]).trim()) {
    return { ...empty, faqsSkipped: faqResult.skipped, reason: "files unchanged after write" };
  }

  const parts: string[] = [];
  if (faqResult.published > 0) {
    parts.push(`${faqResult.published} FAQ ${faqResult.published === 1 ? "answer" : "answers"}`);
  }
  if (linkResult.published > 0) {
    parts.push(`${linkResult.published} internal ${linkResult.published === 1 ? "link" : "links"}`);
  }

  const date = new Date().toISOString().split("T")[0];
  git(repo, ["commit", "-m", `seo: add ${parts.join(" and ")} (${date})`]);
  git(repo, ["push", "origin", SITE_BRANCH]);

  console.log(`Pushed ${parts.join(" and ")}.`);

  return {
    faqsPublished: faqResult.published,
    faqsSkipped: faqResult.skipped,
    linksPublished: linkResult.published,
    faqPaths: faqResult.paths,
    linkPaths: linkResult.paths,
  };
}
